In [ ]:
!pip install gym

In [ ]:
import gym
import numpy as np
import random

In [ ]:
env=gym.make("Taxi-v2")  #creating taxiv2 environment import it from open ai gym
env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [ ]:
action_size= env.action_space.n
state_size= env.observation_space.n
qtable= np.zeros((state_size,action_size))
print(action_size)
print(state_size)
print(qtable)

6
500
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# creating hyperparameters


In [ ]:
total_episodes= 100000
total_test_episodes= 200
max_steps= 99                 #allowed per episode
learning_rate= 0.7            #learning rate for delta(w)
gamma= 0.618                  #discounting rate
 #exploration and exploitation parameters
epsilon= 1.0
max_epsilon= 1.0
min_epsilon= 0.01
decay_rate= 0.01

#Q learning algorithm

In [ ]:
for episode in range(total_episodes):    #total life
  state= env.reset()            #reset environment
  step= 0
  done= False
  
  for step in range(max_steps):
    exp_exp_tradeoff= random.uniform(0,1)
                                              #exploration and exploitation tradeoff
    if exp_exp_tradeoff > epsilon:
      action= np.argmax(qtable[state,:])
    else:
      action= env.action_space.sample()
    
    new_state, reward, done, info = env.step(action)
    #this step function takes action given as parameter after every step takes in action and returns 4 other parameters
    #update q values using bellman equation
    
    qtable[state, action]= qtable[state, action] + learning_rate*(reward + gamma*np.max(qtable[new_state, :])-qtable[state, action])
    
    state=new_state
    if done== True:     #when done finish the episode
      break
  episode+=1
  epsilon= min_epsilon + (max_epsilon-min_epsilon)*np.exp(-decay_rate*episode)

# using q learning algorithm to play taxi

In [ ]:
env.reset()
rewards=[]

for episode in range(total_test_episodes):
  state= env.reset()
  step= 0
  done= False
  total_rewards=0
  print("*************************")
  print('episode:', episode)
  
  for step in range(max_steps):
    env.render()
    action= np.argmax(qtable[state,:])
    new_state, reward, done, info =env.step(action)
    total_rewards+= reward
    
    if done:
      rewards.append(total_rewards)
      print('score', total_rewards)
      break
    state= new_state
env.close()    
print("score over time:" + str(sum(rewards)/total_test_episodes))

*************************
episode: 0
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : |_: |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : 

In [ ]:
_